title: <p align="center"> Sawan Sabbu </p>
logo: /assets/img/passportPhotoSawan.jpg

description:
  <p align="center">
  <a href="https://github.com/sawan121989">GitHub</a>
  
  <br>   
  I'm working as Sr. Technical Lead in Birlasoft Limited.
  Have total of 11 years of working eperience in Data Engineering and ETL Development 
  <br>
  </p>



theme: jekyll-theme-minimal
