title: <p align="center"> Sawan Sabbu </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="">Resume</a> |
  <a href="">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
  I'm working as Sr Technical Lead in Birlasoft.
  I have 11 years of experience in 
  Data Engineering and ETL Delepemnt
  <br>
  </p>



theme: jekyll-theme-minimal
